/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as ProtectedExampleProtectedRouteRouteImport } from './routes/_protected/example-protected-route'
import { Route as ProtectedAdminRouteImport } from './routes/_protected/admin'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignOutRouteImport } from './routes/_auth/sign-out'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as ApiHelloRouteImport } from './routes/_api/hello'
import { Route as ProtectedAdminIndexRouteImport } from './routes/_protected/admin/index'
import { Route as ProtectedAdminSettingsRouteImport } from './routes/_protected/admin/settings'
import { Route as ProtectedAdminProjectsRouteImport } from './routes/_protected/admin/projects'
import { Route as ProtectedAdminProfileRouteImport } from './routes/_protected/admin/profile'
import { Route as ProtectedAdminMessagesRouteImport } from './routes/_protected/admin/messages'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const ProtectedExampleProtectedRouteRoute =
  ProtectedExampleProtectedRouteRouteImport.update({
    id: '/example-protected-route',
    path: '/example-protected-route',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedAdminRoute = ProtectedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignOutRoute = AuthSignOutRouteImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const ApiHelloRoute = ApiHelloRouteImport.update({
  id: '/_api/hello',
  path: '/hello',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAdminIndexRoute = ProtectedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedAdminSettingsRoute = ProtectedAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedAdminProjectsRoute = ProtectedAdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedAdminProfileRoute = ProtectedAdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedAdminMessagesRoute = ProtectedAdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => ProtectedAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/hello': typeof ApiHelloRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-out': typeof AuthSignOutRoute
  '/sign-up': typeof AuthSignUpRoute
  '/admin': typeof ProtectedAdminRouteWithChildren
  '/example-protected-route': typeof ProtectedExampleProtectedRouteRoute
  '/admin/messages': typeof ProtectedAdminMessagesRoute
  '/admin/profile': typeof ProtectedAdminProfileRoute
  '/admin/projects': typeof ProtectedAdminProjectsRoute
  '/admin/settings': typeof ProtectedAdminSettingsRoute
  '/admin/': typeof ProtectedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/hello': typeof ApiHelloRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-out': typeof AuthSignOutRoute
  '/sign-up': typeof AuthSignUpRoute
  '/example-protected-route': typeof ProtectedExampleProtectedRouteRoute
  '/admin/messages': typeof ProtectedAdminMessagesRoute
  '/admin/profile': typeof ProtectedAdminProfileRoute
  '/admin/projects': typeof ProtectedAdminProjectsRoute
  '/admin/settings': typeof ProtectedAdminSettingsRoute
  '/admin': typeof ProtectedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_api/hello': typeof ApiHelloRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-out': typeof AuthSignOutRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_protected/admin': typeof ProtectedAdminRouteWithChildren
  '/_protected/example-protected-route': typeof ProtectedExampleProtectedRouteRoute
  '/_public/': typeof PublicIndexRoute
  '/_protected/admin/messages': typeof ProtectedAdminMessagesRoute
  '/_protected/admin/profile': typeof ProtectedAdminProfileRoute
  '/_protected/admin/projects': typeof ProtectedAdminProjectsRoute
  '/_protected/admin/settings': typeof ProtectedAdminSettingsRoute
  '/_protected/admin/': typeof ProtectedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hello'
    | '/sign-in'
    | '/sign-out'
    | '/sign-up'
    | '/admin'
    | '/example-protected-route'
    | '/admin/messages'
    | '/admin/profile'
    | '/admin/projects'
    | '/admin/settings'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hello'
    | '/sign-in'
    | '/sign-out'
    | '/sign-up'
    | '/example-protected-route'
    | '/admin/messages'
    | '/admin/profile'
    | '/admin/projects'
    | '/admin/settings'
    | '/admin'
  id:
    | '__root__'
    | '/_auth'
    | '/_protected'
    | '/_public'
    | '/_api/hello'
    | '/_auth/sign-in'
    | '/_auth/sign-out'
    | '/_auth/sign-up'
    | '/_protected/admin'
    | '/_protected/example-protected-route'
    | '/_public/'
    | '/_protected/admin/messages'
    | '/_protected/admin/profile'
    | '/_protected/admin/projects'
    | '/_protected/admin/settings'
    | '/_protected/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  ApiHelloRoute: typeof ApiHelloRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_protected/example-protected-route': {
      id: '/_protected/example-protected-route'
      path: '/example-protected-route'
      fullPath: '/example-protected-route'
      preLoaderRoute: typeof ProtectedExampleProtectedRouteRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-out': {
      id: '/_auth/sign-out'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof AuthSignOutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_api/hello': {
      id: '/_api/hello'
      path: '/hello'
      fullPath: '/hello'
      preLoaderRoute: typeof ApiHelloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/admin/': {
      id: '/_protected/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof ProtectedAdminIndexRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/settings': {
      id: '/_protected/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof ProtectedAdminSettingsRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/projects': {
      id: '/_protected/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof ProtectedAdminProjectsRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/profile': {
      id: '/_protected/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof ProtectedAdminProfileRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/messages': {
      id: '/_protected/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof ProtectedAdminMessagesRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
  }
}

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignOutRoute: typeof AuthSignOutRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignOutRoute: AuthSignOutRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedAdminRouteChildren {
  ProtectedAdminMessagesRoute: typeof ProtectedAdminMessagesRoute
  ProtectedAdminProfileRoute: typeof ProtectedAdminProfileRoute
  ProtectedAdminProjectsRoute: typeof ProtectedAdminProjectsRoute
  ProtectedAdminSettingsRoute: typeof ProtectedAdminSettingsRoute
  ProtectedAdminIndexRoute: typeof ProtectedAdminIndexRoute
}

const ProtectedAdminRouteChildren: ProtectedAdminRouteChildren = {
  ProtectedAdminMessagesRoute: ProtectedAdminMessagesRoute,
  ProtectedAdminProfileRoute: ProtectedAdminProfileRoute,
  ProtectedAdminProjectsRoute: ProtectedAdminProjectsRoute,
  ProtectedAdminSettingsRoute: ProtectedAdminSettingsRoute,
  ProtectedAdminIndexRoute: ProtectedAdminIndexRoute,
}

const ProtectedAdminRouteWithChildren = ProtectedAdminRoute._addFileChildren(
  ProtectedAdminRouteChildren,
)

interface ProtectedRouteChildren {
  ProtectedAdminRoute: typeof ProtectedAdminRouteWithChildren
  ProtectedExampleProtectedRouteRoute: typeof ProtectedExampleProtectedRouteRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAdminRoute: ProtectedAdminRouteWithChildren,
  ProtectedExampleProtectedRouteRoute: ProtectedExampleProtectedRouteRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface PublicRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  ApiHelloRoute: ApiHelloRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
